import {it,expect} from 'vitest';
import {MemoryDatabase} from './customer.test.js';
import {Diagnosis} from '../apps/customer/src/diagnosis.js';
import {DIY} from '../apps/customer/src/diy.js';
import {Vision} from '../apps/customer/src/vision.js';
import {AI} from '../apps/customer/src/ai.js';
import {safetyState} from '../apps/customer/src/safety.js';
async function setup() { const db=new MemoryDatabase(); await db.save('homes',{id:'h',user_id:'u'}); const diagnosis=new Diagnosis(db); const row=await diagnosis.start('u',{home_id:'h',text:'Remote batteries empty'}); row.payload.safety=safetyState(); row.payload.classification={classification:'diy'}; row.payload.interview={diy_guide:'remote_batteries'}; await diagnosis.persist(row); return {db,diagnosis,row}; }
it('DIY advances only once and finishes after three verified results',async()=>{const {diagnosis,row}=await setup(); const diy=new DIY(diagnosis); const g=await diy.start('u',{diagnosis_session_id:row.id,preconditions_confirmed:true,tools_available:true}); await diy.result(g.guide_id,'u',{step_index:0,result:'done'}); await expect(diy.result(g.guide_id,'u',{step_index:0,result:'done'})).rejects.toMatchObject({status:409}); await diy.result(g.guide_id,'u',{step_index:1,result:'done'}); expect((await diy.result(g.guide_id,'u',{step_index:2,result:'done'})).status).toBe('completed');});
it.each(['different','failure','stop'])('DIY %s escalates to technician',async result=>{const {diagnosis,row}=await setup(); const diy=new DIY(diagnosis); const g=await diy.start('u',{diagnosis_session_id:row.id,preconditions_confirmed:true,tools_available:true}); expect((await diy.result(g.guide_id,'u',{step_index:0,result})).classification.classification).toBe('technician');});
it('a new hazard immediately prevents the next DIY step',async()=>{const {diagnosis,row}=await setup(); const diy=new DIY(diagnosis); const g=await diy.start('u',{diagnosis_session_id:row.id,preconditions_confirmed:true,tools_available:true}); await diagnosis.message(row.id,'u',{text:'I see smoke'}); const stopped=await diy.result(g.guide_id,'u',{step_index:0,result:'done'}); expect(stopped.status).toBe('stopped'); expect(stopped.classification.classification).toBe('emergency');});
it.each(['normal','difficult','safe_failure'])('vision %s uses the actual stored image and abstains safely',async kind=>{const {db,diagnosis,row}=await setup(); await db.save('attachments',{id:'a',user_id:'u',session_id:row.id,payload:{mime_type:'image/png',base64:'fixture',caption:''}}); const vision=new Vision(diagnosis,new AI(db,async input=>{expect(input.image).toBe('data:image/png;base64,fixture'); if(kind==='safe_failure')throw Error('offline'); return {visual_findings:['Handheld remote'],relevant_component:'Remote',hazard_flags:[],confidence:kind==='normal'?0.9:0.2,explanation:'Visible remote'};})); const result=await vision.assess(row.id,'u',{attachment_id:'a'}); expect(result.available).toBe(kind==='normal'); if(kind!=='normal')expect(result.relevant_component).toBeNull();});
